# Generated by Django 5.0.4 on 2024-05-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticated', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
    ]
